spring.application.name=gateway-service
server.port=8080

# Route Assessment
spring.cloud.gateway.server.webmvc.routes[0].id=assessment-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${ASSESSMENT_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/assessments/**

# JWT
jwt.secret=${JWT_SECRET}

# Logs temporaires
logging.level.org.springframework.security=DEBUG