spring.application.name=assessment-service
server.port=8084

# Patient-service
patient.service.url=${PATIENT_SERVICE_URL:http://localhost:8082}

# Note-service
note.service.url=${NOTE_SERVICE_URL:http://localhost:8083}

# Authentification interne
service.username=${SERVICE_USERNAME}
service.password=${SERVICE_PASSWORD}